cluster:
  master:
    hostname: raspberry-master
    ip: 192.168.0.100
    ssh_port: 22
    user: ubuntu
  name: cointicker-cluster
  workers:
  - hostname: raspberry-worker1
    ip: 192.168.0.101
    ssh_port: 22
    user: ubuntu
  - hostname: raspberry-worker2
    ip: 192.168.0.102
    ssh_port: 22
    user: ubuntu
  - hostname: raspberry-worker3
    ip: 192.168.0.103
    ssh_port: 22
    user: ubuntu
hadoop:
  hdfs:
    namenode: hdfs://raspberry-master:9000
    replication: 3
  home: /opt/hadoop
  version: 3.4.1
  yarn:
    resourcemanager: raspberry-master:8032
hdfs:
  timing:
    daemon_stop_timeout: 10
    format_timeout: 30
    script_timeout: 30
scrapy:
  concurrent_requests: 16
  download_delay: 1
  log_level: INFO
  project_name: cointicker
